In [24]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
import pandas as pd
import seaborn as sns

In [3]:
a = np.array([[3, 1], 
              [0, 2]])
a

array([[3, 1],
       [0, 2]])

In [4]:
b = np.array([1, 0])
a.dot(b)

array([3, 0])

In [5]:
eigenVector = np.array([-1, 1])
a.dot(eigenVector)

array([-2,  2])

In [6]:
#  Find the eigenvector of the matrix
A = np.array([[1,0],[0,-2]])
print(A)

[[ 1  0]
 [ 0 -2]]


In [17]:
eigval, eigvec = la.eig(A)
print(eigval, eigvec)

[ 1.+0.j -2.+0.j] [[1. 0.]
 [0. 1.]]


In [18]:
# we can use the NumPy array method .real to convert the array of eigenvalues to real numbers
eigval = eigval.real
print(eigval)


[ 1. -2.]


In [20]:
# the position of an eigenvalue in the array eigvals correspond to the column in eigvecs with its eigenvector
lambda1 = eigval[1]
print(lambda1)

-2.0


In [22]:
v1 = eigvec[:,1].reshape(2,1)
print(v1)

[[0.]
 [1.]]
