In [1]:
import pandas as pd
import numpy as np

In [2]:
# One dimensional numpy array
np.array([1, 2, 10, 4, 2, 3])

array([ 1,  2, 10,  4,  2,  3])

In [3]:
# Two dimensional numpy array
np.array([[1, 10, 20], [23, 23, 234]])

array([[  1,  10,  20],
       [ 23,  23, 234]])

In [4]:
# Generate a (x, y) shape of numpy array

a = np.random.randint(1, 100, size=(1, 5))
b = np.random.randint(1, 100, size=(6, 1))
print(a)
print(b)

[[95 67 68 74 83]]
[[56]
 [57]
 [17]
 [30]
 [40]
 [89]]


In [5]:
# The number of columns of the 1st matrix must equal the number of rows of the 2nd matrix.
# And the result will have the same number of rows as the 1st matrix, and the same number of columns as the 2nd matrix.
result = a * b
print(result)

[[5320 3752 3808 4144 4648]
 [5415 3819 3876 4218 4731]
 [1615 1139 1156 1258 1411]
 [2850 2010 2040 2220 2490]
 [3800 2680 2720 2960 3320]
 [8455 5963 6052 6586 7387]]


In [7]:
# Get me the second column
result[0:, 1]

array([3752, 3819, 1139, 2010, 2680, 5963])

In [8]:
# Get me the first column
# Get me the first and second column
# Get me from the 0th row 4th row to 2rd column and 4th column
result[0:4, 2:4]

array([[3808, 4144],
       [3876, 4218],
       [1156, 1258],
       [2040, 2220]])

In [9]:
# Convert these into a dataframe
df = pd.DataFrame.from_records(result, columns=["Age", "Height", "Score", "Rating", "Distance"])
df

Age  Height  Score  Rating  Distance
0  5320    3752   3808    4144      4648
1  5415    3819   3876    4218      4731
2  1615    1139   1156    1258      1411
3  2850    2010   2040    2220      2490
4  3800    2680   2720    2960      3320
5  8455    5963   6052    6586      7387

In [10]:
df["Age"]

0    5320
1    5415
2    1615
3    2850
4    3800
5    8455
Name: Age, dtype: int64

In [16]:
df1 = df[df["Height"]>= 2000]
print(df1)

In [17]:
df1

Age  Height  Score  Rating  Distance
0  5320    3752   3808    4144      4648
1  5415    3819   3876    4218      4731
3  2850    2010   2040    2220      2490
4  3800    2680   2720    2960      3320
5  8455    5963   6052    6586      7387