In [1]:
import pandas as pd
import numpy as np

In [6]:
# One dimensional numpy array
np.array([1, 2, 10, 4, 2, 3])

array([ 1,  2, 10,  4,  2,  3])

In [5]:
# Two dimensional numpy array
np.array([[1, 10, 20], [23, 23, 234]])

array([[  1,  10,  20],
       [ 23,  23, 234]])

In [30]:
# Generate a (x, y) shape of numpy array

a = np.random.randint(1, 100, size=(1, 5))
b = np.random.randint(1, 100, size=(6, 1))
print(a)
print(b)

[[37  7 43 13 80]]
[[ 8]
 [86]
 [58]
 [11]
 [ 8]
 [79]]


In [32]:
# The number of columns of the 1st matrix must equal the number of rows of the 2nd matrix.
# And the result will have the same number of rows as the 1st matrix, and the same number of columns as the 2nd matrix.
result = a * b
print(result)

[[ 296   56  344  104  640]
 [3182  602 3698 1118 6880]
 [2146  406 2494  754 4640]
 [ 407   77  473  143  880]
 [ 296   56  344  104  640]
 [2923  553 3397 1027 6320]]


In [43]:
# Get me the second column
result[0:, 1]

array([ 56, 602, 406,  77,  56, 553])

In [45]:
# Get me the first column
# Get me the first and second column
# Get me from the 0th row 4th row to 2rd column and 4th column
result[0:4, 2:5]

array([[ 344,  104,  640],
       [3698, 1118, 6880],
       [2494,  754, 4640],
       [ 473,  143,  880]])

In [49]:
# Convert these into a dataframe
df = pd.DataFrame.from_records(result, columns=["Age", "Height", "Score", "Rating", "Distance"])
df

Age  Height  Score  Rating  Distance
0   296      56    344     104       640
1  3182     602   3698    1118      6880
2  2146     406   2494     754      4640
3   407      77    473     143       880
4   296      56    344     104       640
5  2923     553   3397    1027      6320

In [50]:
df["Age"]

0     296
1    3182
2    2146
3     407
4     296
5    2923
Name: Age, dtype: int64