In [1]:
import pandas as pd
import numpy as np

In [2]:
# One dimensional numpy array
np.array([1, 2, 10, 4, 2, 3])

array([ 1,  2, 10,  4,  2,  3])

In [5]:
# Two dimensional numpy array
arr = np.array([[1, 10, 20], [23, 23, 234]])

In [6]:
print(arr.shape)

(2, 3)


In [9]:
arr2 = np.zeros([4, 3], dtype = int)
arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
# Generate a (x, y) shape of numpy array

a = np.random.randint(1, 100, size=(1, 5))
b = np.random.randint(1, 100, size=(6, 1))
print(a)
print(b)

[[36 81 44 90 81]]
[[76]
 [ 3]
 [84]
 [41]
 [64]
 [85]]


In [11]:
# The number of columns of the 1st matrix must equal the number of rows of the 2nd matrix.
# And the result will have the same number of rows as the 1st matrix, and the same number of columns as the 2nd matrix.
result = a * b
print(result)

[[2736 6156 3344 6840 6156]
 [ 108  243  132  270  243]
 [3024 6804 3696 7560 6804]
 [1476 3321 1804 3690 3321]
 [2304 5184 2816 5760 5184]
 [3060 6885 3740 7650 6885]]


In [13]:
# Get me the second column
result[0:, 1]

array([6156,  243, 6804, 3321, 5184, 6885])

In [15]:
print(result[0:3,0:4])

[[2736 6156 3344 6840]
 [ 108  243  132  270]
 [3024 6804 3696 7560]]


In [17]:
print(result[0:4, 2:4])
result[0:, 0:1]

[[3344 6840]
 [ 132  270]
 [3696 7560]
 [1804 3690]]


array([[2736],
       [ 108],
       [3024],
       [1476],
       [2304],
       [3060]])

In [18]:
# Get me the first column
# Get me the first and second column
# Get me from the 0th row 4th row to 2rd column and 4th column
result[0:4, 2:5]

array([[3344, 6840, 6156],
       [ 132,  270,  243],
       [3696, 7560, 6804],
       [1804, 3690, 3321]])

In [19]:
# Convert these into a dataframe
df = pd.DataFrame.from_records(result, columns=["Age", "Height", "Score", "Rating", "Distance"])
df

Age  Height  Score  Rating  Distance
0  2736    6156   3344    6840      6156
1   108     243    132     270       243
2  3024    6804   3696    7560      6804
3  1476    3321   1804    3690      3321
4  2304    5184   2816    5760      5184
5  3060    6885   3740    7650      6885

In [20]:
df["Age"]

0    2736
1     108
2    3024
3    1476
4    2304
5    3060
Name: Age, dtype: int64

In [32]:
df2 = df["Age"]*df["Distance"]
df2.mean()

12559698.0

In [25]:
df1 = df[df["Height"]>= 3000]
print(df1)

    Age  Height  Score  Rating  Distance
0  2736    6156   3344    6840      6156
2  3024    6804   3696    7560      6804
3  1476    3321   1804    3690      3321
4  2304    5184   2816    5760      5184
5  3060    6885   3740    7650      6885


In [38]:
df3 = df[df["Height"]>=3000]
x = df3["Score"]*df3["Rating"]
print(x)
x.mean()

0    22872960
2    27941760
3     6656760
4    16220160
5    28611000
dtype: int64


20460528.0